{"name": "test_login_locked_out_user", "status": "passed", "steps": [{"name": "Открываем страницу логина", "status": "passed", "start": 1758713479624, "stop": 1758713480656}, {"name": "Логинимся пользователем 'locked_out_user'", "status": "passed", "parameters": [{"name": "username", "value": "'locked_out_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1758713480656, "stop": 1758713480730}, {"name": "Получаем текст ошибки при логине", "status": "passed", "start": 1758713480730, "stop": 1758713480735}], "start": 1758713479624, "stop": 1758713480735, "uuid": "dac31e96-4571-420a-b751-a49dfc988f06", "historyId": "364d39b2be4aad43ae744509fff753ed", "testCaseId": "364d39b2be4aad43ae744509fff753ed", "fullName": "tests.ui.test_auth#test_login_locked_out_user", "labels": [{"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "DESKTOP-JVPC402"}, {"name": "thread", "value": "12016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_auth"}], "titlePath": ["tests", "ui", "test_auth.py"]}