{"name": "test_login_locked_out_user", "status": "passed", "steps": [{"name": "Открываем страницу логина", "status": "passed", "start": 1758713977804, "stop": 1758713978806}, {"name": "Логинимся пользователем 'locked_out_user'", "status": "passed", "parameters": [{"name": "username", "value": "'locked_out_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1758713978807, "stop": 1758713978877}, {"name": "Получаем текст ошибки при логине", "status": "passed", "start": 1758713978877, "stop": 1758713978882}], "start": 1758713977804, "stop": 1758713978882, "uuid": "72ef2847-ebfa-43ac-858a-e2724183f68a", "historyId": "364d39b2be4aad43ae744509fff753ed", "testCaseId": "364d39b2be4aad43ae744509fff753ed", "fullName": "tests.ui.test_auth#test_login_locked_out_user", "labels": [{"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "DESKTOP-JVPC402"}, {"name": "thread", "value": "17916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_auth"}], "titlePath": ["tests", "ui", "test_auth.py"]}